# Generated by Django 2.1.9 on 2022-02-05 15:28

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_task'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='task',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
