# Generated by Django 4.0.2 on 2022-02-06 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220205_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['-creationDate']},
        ),
    ]
